### ISSUE TITLE
Support dot notation for built-in translate function

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-permission#1]
Add support to the built-in translate function (`resourceToPropertyIdentifier`) to accept properties that are dot-separated to indicate a path in the resource. For example:

For the resource:

``` json
{
  "a": {
    "b": "c"
  }
}
```

Calling `resourceToPropertyIdentifier('a.b')` would use the value `'c'`.

This line would need to be modified:

https://github.com/digitalbazaar/bedrock-permission/blob/434d3935a3839014d4514dc46129030faef7bb04/lib/permission.js#L347

Some code from here:

http://stackoverflow.com/questions/15222493/pick-method-to-match-the-sub-property-in-an-objects-array

Could be used/modified to make it work. However, we want to continue to support the ability to pass properties with actual dots in them, so we would also want '/' escape support for dots. We should provide a new API call to dot-escape a property as well.

**Comment by davidlehn** [comment]
It's not the same use case, but % encoding of '.' and other illegal mongodb chars in object keys is done via encode() and decode() functions. Might be able to use similar code.
https://github.com/digitalbazaar/bedrock-mongodb/blob/master/lib/database.js
