### ISSUE TITLE
Promise implementation broken after fixing callback implementation

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-permission#16]
This commit works with the `callback` pattern, but is broken with the promise pattern:

https://github.com/digitalbazaar/bedrock-permission/commit/e6ba138060ca2dcf164ad88ac77242c25d7a4d10

Now it's broken when:
```
await brPermission.checkPermission(
  actor, PERMISSIONS.LEDGER_CREATE, {
    resource: node,
    translate: 'owner'
  });
```

In this case, `callback` is not defined (not a function).

**Comment by mattcollier** [comment]
I can add that node's callbackify is no better at handling an `undefined` argument.

**Comment by dlongley** [comment]
Better to be broken with the non-promise version than with the promise one. But we should be able to fix it so it works with both as we've done with all the other things.

**Comment by dlongley** [comment]
Does it just also need to check if `callback` is defined (or is a function, rather)?
